[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm install --omit=dev"]

[phases.build]
cmds = ["cd server && npm run build || true"]

[start]
cmd = "cd server && node index.js"
