[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm install --omit=dev && node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
