# Android SDK Local Setup Script
# This script sets up Android SDK environment variables and verifies installation

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Android SDK Local Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Default Android SDK location
$defaultSdkPath = "$env:LOCALAPPDATA\Android\Sdk"
$projectSdkPath = "$PSScriptRoot\android-sdk"

# Check if SDK exists in default location
if (Test-Path $defaultSdkPath) {
    Write-Host "✓ Android SDK found at: $defaultSdkPath" -ForegroundColor Green
    $sdkPath = $defaultSdkPath
} else {
    Write-Host "✗ Android SDK not found in default location" -ForegroundColor Yellow
    Write-Host "  Checking for project-local SDK..." -ForegroundColor Yellow
    
    if (Test-Path $projectSdkPath) {
        Write-Host "✓ Project-local SDK found at: $projectSdkPath" -ForegroundColor Green
        $sdkPath = $projectSdkPath
    } else {
        Write-Host "✗ No Android SDK found. Please install Android Studio or SDK tools." -ForegroundColor Red
        Write-Host ""
        Write-Host "To install Android SDK:" -ForegroundColor Yellow
        Write-Host "  1. Download Android Studio from: https://developer.android.com/studio" -ForegroundColor Yellow
        Write-Host "  2. Or download command-line tools from: https://developer.android.com/studio#command-tools" -ForegroundColor Yellow
        exit 1
    }
}

# Verify SDK components
Write-Host ""
Write-Host "Verifying SDK components..." -ForegroundColor Cyan

$components = @{
    "Platform Tools" = "platform-tools"
    "Build Tools" = "build-tools"
    "Platforms" = "platforms"
    "NDK" = "ndk"
}

$allPresent = $true
foreach ($component in $components.GetEnumerator()) {
    $componentPath = Join-Path $sdkPath $component.Value
    if (Test-Path $componentPath) {
        if ($component.Value -eq "build-tools") {
            $versions = Get-ChildItem $componentPath -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name
            if ($versions) {
                Write-Host "  ✓ $($component.Key): $($versions -join ', ')" -ForegroundColor Green
            } else {
                Write-Host "  ✗ $($component.Key): Directory empty" -ForegroundColor Red
                $allPresent = $false
            }
        } elseif ($component.Value -eq "platforms") {
            $versions = Get-ChildItem $componentPath -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name
            if ($versions) {
                Write-Host "  ✓ $($component.Key): $($versions -join ', ')" -ForegroundColor Green
            } else {
                Write-Host "  ✗ $($component.Key): No platforms installed" -ForegroundColor Red
                $allPresent = $false
            }
        } else {
            Write-Host "  ✓ $($component.Key): Present" -ForegroundColor Green
        }
    } else {
        Write-Host "  ✗ $($component.Key): Missing" -ForegroundColor Red
        $allPresent = $false
    }
}

# Set environment variables for current session
Write-Host ""
Write-Host "Setting environment variables for current session..." -ForegroundColor Cyan
$env:ANDROID_HOME = $sdkPath
$env:ANDROID_SDK_ROOT = $sdkPath
$env:PATH = "$sdkPath\platform-tools;$sdkPath\tools;$env:PATH"

Write-Host "  ✓ ANDROID_HOME = $env:ANDROID_HOME" -ForegroundColor Green
Write-Host "  ✓ ANDROID_SDK_ROOT = $env:ANDROID_SDK_ROOT" -ForegroundColor Green

# Update local.properties if in React Native project
$localPropertiesPath = Join-Path $PSScriptRoot "android\local.properties"
if (Test-Path (Join-Path $PSScriptRoot "android")) {
    Write-Host ""
    Write-Host "Updating local.properties..." -ForegroundColor Cyan
    
    $sdkDir = $sdkPath -replace '\\', '\\'
    $ndkPath = Join-Path $sdkPath "ndk"
    
    if (Test-Path $ndkPath) {
        $ndkVersions = Get-ChildItem $ndkPath -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Name
        if ($ndkVersions) {
            $ndkDir = Join-Path $ndkPath $ndkVersions
            $ndkDir = $ndkDir -replace '\\', '\\'
        } else {
            $ndkDir = ""
        }
    } else {
        $ndkDir = ""
    }
    
    $properties = @"
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
# Generated by setup-android-sdk.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
sdk.dir=$sdkDir
"@
    
    if ($ndkDir) {
        $properties += "`nndk.dir=$ndkDir"
    }
    
    Set-Content -Path $localPropertiesPath -Value $properties -Force
    Write-Host "  ✓ Updated android\local.properties" -ForegroundColor Green
}

# Verify adb
Write-Host ""
Write-Host "Verifying ADB..." -ForegroundColor Cyan
$adbPath = Join-Path $sdkPath "platform-tools\adb.exe"
if (Test-Path $adbPath) {
    try {
        $adbVersion = & $adbPath version 2>&1
        Write-Host "  ✓ ADB is working" -ForegroundColor Green
    } catch {
        Write-Host "  ✗ ADB found but not working" -ForegroundColor Red
    }
} else {
    Write-Host "  ✗ ADB not found" -ForegroundColor Red
}

# Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "SDK Location: $sdkPath" -ForegroundColor White
Write-Host "ANDROID_HOME: $env:ANDROID_HOME" -ForegroundColor White
Write-Host "ANDROID_SDK_ROOT: $env:ANDROID_SDK_ROOT" -ForegroundColor White

if ($allPresent) {
    Write-Host ""
    Write-Host "✓ Android SDK is properly configured!" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "⚠ Some SDK components are missing. Install them via Android Studio SDK Manager." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Note: Environment variables are set for this session only." -ForegroundColor Yellow
Write-Host "To make them permanent, add to System Environment Variables:" -ForegroundColor Yellow
Write-Host "  ANDROID_HOME = $sdkPath" -ForegroundColor White
Write-Host "  ANDROID_SDK_ROOT = $sdkPath" -ForegroundColor White
Write-Host "  Add to PATH: $sdkPath\platform-tools;$sdkPath\tools" -ForegroundColor White


